function report = test_speed_planning(run_project_cases)
% Regression tests for LMSC/SPU seventh-order speed planning.
%
% test_speed_planning(false) runs eight synthetic cases only.
% test_speed_planning(true) also evaluates 5stars.csv and exports one
% Pareto candidate into a temporary directory. The default is true.

if nargin < 1
    run_project_cases = true;
end
project_root = fileparts(mfilename('fullpath'));
remove_legacy_vecnorm_shadow(project_root);
addpath(project_root);
cfg = trajectory_config(project_root);
test_dynamic_dimensions(cfg);
test_unique_chromosome_floor(cfg);
test_dynamic_lmsc_clustering(cfg);
test_xyz_vibration_metric(cfg);
test_machine_resonance(cfg);
test_analytic_nurbs_derivatives();
test_geometric_jerk_speed_limit(cfg);
test_pareto_time_filter(cfg);
test_global_time_scaling_switch(cfg);
test_xyz_snap_limit_switch(cfg);
test_optimization_time_memory_guard(cfg);
test_shared_lmsc_jerk_transition(cfg);

% These regression cases assert that every returned trajectory is feasible.
% Keep the project setting selectable, but enable the documented global
% feasibility fallback in the isolated test configuration. With the fallback
% disabled, difficult candidates are intentionally allowed to remain
% infeasible and are penalized by evaluate_trajectory instead.
test_cfg = cfg;
test_cfg.speed.enable_global_time_scaling = true;
if ~cfg.speed.enable_global_time_scaling
    fprintf(['Speed-planning regression uses global time scaling as a ' ...
        'feasibility fallback; the project configuration remains disabled.\n']);
end

t = linspace(0, 1, 601)';
straight_3d = 3000 * t * [1 1 1] / sqrt(3);
line_x = linspace(0, 800, 401)';
corner_reference_speed = min([test_cfg.limits.Vmax, ...
    test_cfg.limits.xyz_vmax(:)']);
corner_target_speed = max(0.8 * corner_reference_speed, ...
    100 * test_cfg.speed.velocity_tolerance);
turn_radius = corner_target_speed^2 / max(test_cfg.limits.Acmax, eps);
turn_angle = linspace(0, pi/2, 201)';
single_corner = [line_x, zeros(size(line_x)), zeros(size(line_x)); ...
    800 + turn_radius*sin(turn_angle(2:end)), ...
    turn_radius*(1-cos(turn_angle(2:end))), ...
    zeros(numel(turn_angle)-1, 1)];
synthetic = {
    'three_dimensional_line', 500 * t * [1 0.4 0.2], ones(1, test_cfg.nsga.num_time_nodes); ...
    'single_smooth_corner', single_corner, ones(1, test_cfg.nsga.num_time_nodes); ...
    'multiple_curvature_peaks', [800*t, 20*sin(6*pi*t)+6*sin(14*pi*t), 5*sin(4*pi*t)], ones(1, test_cfg.nsga.num_time_nodes); ...
    'very_short_path', [0.02*t, zeros(size(t)), zeros(size(t))], ones(1, test_cfg.nsga.num_time_nodes); ...
    'short_path_below_vmax', [20*t, zeros(size(t)), zeros(size(t))], ones(1, test_cfg.nsga.num_time_nodes); ...
    'near_zero_curvature_line', [1000*t, 1e-6*sin(2*pi*t), zeros(size(t))], ones(1, test_cfg.nsga.num_time_nodes); ...
    'speed_nodes_lower_bound', straight_3d, test_cfg.bounds.time_lb; ...
    'speed_nodes_upper_bound', straight_3d, test_cfg.bounds.time_ub};

template = struct('name', "", 'passed', false, 'total_time', NaN, ...
    'lmsc_count', 0, 'spu_count', 0, 'constraint_iterations', 0, ...
    'global_time_scale', 1, 'max_path_ratio', NaN, 'max_xyz_ratio', NaN);
report = repmat(template, 0, 1);
case_data = cell(size(synthetic, 1), 1);

for i = 1:size(synthetic, 1)
    fprintf('Running speed-planning case %d/%d: %s ...\n', ...
        i, size(synthetic, 1), synthetic{i, 1});
    [case_result, case_report] = run_synthetic_case( ...
        synthetic{i, 1}, synthetic{i, 2}, synthetic{i, 3}, test_cfg);
    report(end + 1, 1) = case_report; %#ok<AGROW>
    case_data{i} = case_result;
end

% The lower speed-node bound must not produce a shorter traversal than the
% upper bound on the same geometry.
assert(case_data{7}.motion.time(end) > case_data{8}.motion.time(end) + 1e-6, ...
    'Speed-node lower and upper bounds did not produce different traversal times.');

% The continuous reachability envelope must not become more conservative
% merely because the same straight path is sampled more densely.
coarse_S = linspace(0, 500, 101)';
fine_S = linspace(0, 500, 1001)';
coarse_profile = forward_backward_scan(coarse_S, ...
    cfg.limits.Vmax * ones(size(coarse_S)), cfg);
fine_profile = forward_backward_scan(fine_S, ...
    cfg.limits.Vmax * ones(size(fine_S)), cfg);
peak_tolerance = max(cfg.speed.velocity_tolerance, cfg.limits.Vmax * 1e-10);
assert(abs(max(coarse_profile.V) - max(fine_profile.V)) <= peak_tolerance, ...
    'Reachable peak speed depends on arc-length sampling density.');

% A single curvature peak must cause deceleration before the peak rather
% than a pointwise speed clip at the peak itself.
corner = case_data{2};
n_corner = numel(corner.geom.kappa);
interior = max(2, round(0.1*n_corner)):min(n_corner-1, round(0.9*n_corner));
[~, relative_peak_index] = max(corner.geom.kappa(interior));
peak_index = interior(relative_peak_index);
assert(corner.constraints.base_active_constraint(peak_index) == "curvature", ...
    ['The smooth-corner test did not activate the curvature speed limit; ' ...
    'active constraint is %s (v curvature %.9g, v command %.9g, ' ...
    'v axis %.9g, radius %.9g).'], ...
    corner.constraints.base_active_constraint(peak_index), ...
    corner.constraints.v_curvature(peak_index), ...
    corner.constraints.v_command(peak_index), ...
    corner.constraints.v_axis(peak_index), turn_radius);
preceding = max(2, peak_index - 200):peak_index;
planned_corner_speed = corner.constraints.v_planned;
assert(any(diff(planned_corner_speed(preceding)) < -cfg.speed.velocity_tolerance), ...
    'No anticipatory deceleration was detected before the curvature peak.');

if run_project_cases
    lower = [test_cfg.bounds.weights_lb test_cfg.bounds.time_lb ...
        test_cfg.bounds.jerk_utilization_lb];
    upper = [test_cfg.bounds.weights_ub test_cfg.bounds.time_ub ...
        test_cfg.bounds.jerk_utilization_ub];
    x = 0.5 * (lower + upper);
    real_result = evaluate_trajectory(x, test_cfg, true);
    if test_cfg.lmsc_jerk_boundary.enabled && ...
            test_cfg.lmsc_jerk_boundary.evaluate_during_objective
        assert(isfield(real_result, 'lmsc_jerk_boundary_search') && ...
                real_result.lmsc_jerk_boundary_search.evaluated_during_objective, ...
            'Shared endpoint-jerk utilization was not evaluated in the objective.');
    end
    assert(real_result.constraint.time_smoothing_enabled, ...
        'Selected-solution global time smoothing was not attempted.');
    verify_motion('real_5stars_input', real_result.motion, real_result.xyz, ...
        real_result.constraints, real_result.arc.S(end), test_cfg);
    report(end + 1, 1) = make_report('real_5stars_input', real_result.motion, ...
        real_result.xyz, real_result.constraint.iterations);

    report(end + 1, 1) = test_temporary_pareto_export(test_cfg);
end

assert(all([report.passed]), 'At least one speed-planning test failed.');
fprintf('All %d speed-planning cases passed.\n', numel(report));
disp(struct2table(report));
end

function [data, item] = run_synthetic_case(name, points, speed_nodes, cfg)
S = [0; cumsum(vecnorm(diff(points), 2, 2))];
geom = compute_curvature(points, S);
constraints = generate_velocity_constraints(geom.kappa, geom.tangent, ...
    cfg, S, speed_nodes);
[constraints, profile, motion, xyz, diagnostics] = plan_speed_profile( ...
    points, S, geom, constraints, speed_nodes, cfg);
verify_motion(name, motion, xyz, constraints, S(end), cfg);
compact_xyz = xyz_motion(points, S, motion, cfg, [], true);
full_ratios = [xyz.max_velocity_ratio, xyz.max_acceleration_ratio, ...
    xyz.max_jerk_ratio, xyz.max_snap_ratio];
compact_ratios = [compact_xyz.max_velocity_ratio, ...
    compact_xyz.max_acceleration_ratio, compact_xyz.max_jerk_ratio, ...
    compact_xyz.max_snap_ratio];
ratio_tolerance = 1e-10 * max(1, max(abs(full_ratios)));
assert(all(abs(compact_ratios - full_ratios) <= ratio_tolerance) && ...
        compact_xyz.feasible == xyz.feasible, ...
    '%s: compact XYZ constraint evaluation differs from the full result.', name);
if cfg.speed.enable_global_time_scaling && ...
        cfg.speed.minimize_global_time_scale && ...
        diagnostics.global_time_scale > 1
    refinement_tolerance = ...
        cfg.speed.global_time_scale_refinement_tolerance * ...
        max(diagnostics.global_time_scale, 1);
    assert(diagnostics.global_time_scale >= ...
            diagnostics.global_time_scale_lower_bound && ...
            diagnostics.global_time_scale - ...
            diagnostics.global_time_scale_lower_bound <= ...
            refinement_tolerance + 10*eps(diagnostics.global_time_scale), ...
        '%s: minimized global-time-scale bracket did not converge.', name);
end

data.geom = geom;
data.constraints = constraints;
data.profile = profile;
data.motion = motion;
data.xyz = xyz;
item = make_report(name, motion, xyz, diagnostics.iterations);
end

function test_global_time_scaling_switch(cfg)
if cfg.speed.enable_global_time_scaling
    return
end

t = linspace(0, 1, 101)';
points = [20*t, zeros(size(t)), zeros(size(t))];
S = [0; cumsum(vecnorm(diff(points), 2, 2))];
geom = compute_curvature(points, S);
speed_nodes = ones(1, cfg.nsga.num_time_nodes);
constraints = generate_velocity_constraints(geom.kappa, geom.tangent, ...
    cfg, S, speed_nodes);
[~, ~, motion, ~, diagnostics] = plan_speed_profile( ...
    points, S, geom, constraints, speed_nodes, cfg);
assert(~diagnostics.global_time_scaling_enabled && ...
        diagnostics.global_time_scaling_iterations == 0 && ...
        abs(motion.constraint_scale - 1) <= cfg.speed.velocity_tolerance, ...
    'The disabled global-time-scaling switch was not respected.');
end

function test_optimization_time_memory_guard(cfg)
t = linspace(0, 1, 101)';
points = [20*t, zeros(size(t)), zeros(size(t))];
S = [0; cumsum(vecnorm(diff(points), 2, 2))];
geom = compute_curvature(points, S);
speed_nodes = ones(1, cfg.nsga.num_time_nodes);
constraints = generate_velocity_constraints(geom.kappa, geom.tangent, ...
    cfg, S, speed_nodes);
caught = false;
try
    plan_speed_profile(points, S, geom, constraints, speed_nodes, cfg, ...
        [], cfg.interpolation.Ts);
catch ME
    caught = strcmp(ME.identifier, ...
        'plan_speed_profile:MaximumTimeExceeded');
    if ~caught
        rethrow(ME)
    end
end
assert(caught, ...
    'The optimization time-memory guard did not reject an oversized candidate.');
end

function verify_motion(name, motion, xyz, constraints, total_length, cfg)
tol = max(100 * cfg.speed.velocity_tolerance, 1e-7);
assert(all(isfinite(motion.time)), '%s: nonfinite time.', name);
assert(all(isfinite(motion.path_velocity)), '%s: nonfinite velocity.', name);
assert(all(isfinite(motion.path_acceleration)), '%s: nonfinite acceleration.', name);
assert(all(isfinite(motion.path_jerk)), '%s: nonfinite jerk.', name);
assert(all(diff(motion.time) > 0), '%s: time is not strictly increasing.', name);
assert(all(diff(motion.S) >= -cfg.speed.distance_tolerance), ...
    '%s: S is not monotone.', name);
assert(abs(motion.S(end) - total_length) <= max(tol, total_length * 1e-10), ...
    '%s: final S does not equal total length.', name);
assert(max(abs(motion.path_velocity([1 end]))) <= tol, ...
    '%s: endpoint velocity is not zero.', name);
assert(max(abs(motion.path_acceleration([1 end]))) <= tol, ...
    '%s: endpoint acceleration is not zero.', name);
assert(max(abs(motion.path_jerk([1 end]))) <= tol, ...
    '%s: endpoint jerk is not zero.', name);
assert(numel(motion.lmsc_jerk) == numel(motion.lmsc.indices) && ...
        all(isfinite(motion.lmsc_jerk)), ...
    '%s: invalid LMSC shared-jerk vector.', name);
assert(numel(motion.spu_peak_jerk) == numel(motion.spus) && ...
        all(isfinite(motion.spu_peak_jerk)), ...
    '%s: invalid SPU peak shared-jerk vector.', name);
assert(max(abs([motion.lmsc_jerk(:); motion.spu_peak_jerk(:)])) <= ...
        cfg.limits.Jmax * (1 + tol), ...
    '%s: a shared jerk boundary exceeds Jmax.', name);

limit_t = interp1(constraints.S, constraints.v_planning_limit, ...
    motion.S, 'linear', 'extrap');
[limit_violation, violation_id] = max(motion.path_velocity - limit_t);
assert(limit_violation <= tol, ...
    ['%s: planned speed exceeds the local speed limit by %.9g at ' ...
    'S = %.9g (planned %.9g, limit %.9g).'], name, limit_violation, ...
    motion.S(violation_id), motion.path_velocity(violation_id), ...
    limit_t(violation_id));
assert(max(abs(motion.path_acceleration)) <= cfg.limits.Amax * (1 + tol), ...
    '%s: path acceleration exceeds Amax.', name);
assert(max(abs(motion.path_jerk)) <= cfg.limits.Jmax * (1 + tol), ...
    '%s: path jerk exceeds Jmax.', name);

assert(size(xyz.points, 1) == numel(motion.time), ...
    '%s: XYZ and time array lengths differ.', name);
assert(size(xyz.velocity, 1) == numel(motion.time), ...
    '%s: XYZ velocity and time array lengths differ.', name);
axis_tolerance = max(tol, max(cfg.limits.xyz_jmax) * 1e-9);
assert(all(max(abs(xyz.velocity), [], 1) <= cfg.limits.xyz_vmax + axis_tolerance), ...
    '%s: XYZ velocity limit exceeded.', name);
assert(all(max(abs(xyz.acceleration), [], 1) <= cfg.limits.xyz_amax + axis_tolerance), ...
    '%s: XYZ acceleration limit exceeded.', name);
assert(all(max(abs(xyz.jerk), [], 1) <= cfg.limits.xyz_jmax + axis_tolerance), ...
    '%s: XYZ jerk limit exceeded.', name);
if xyz_snap_limit_enabled(cfg)
    snap_tolerance = max(tol, max(cfg.limits.xyz_smax) * 1e-9);
    assert(all(max(abs(xyz.snap), [], 1) <= ...
            cfg.limits.xyz_smax + snap_tolerance), ...
        '%s: XYZ snap (jerk-slope) limit exceeded.', name);
end
assert(motion.validation.continuous, '%s: S/V/A/J join continuity failed.', name);
assert(motion.validation.feasible && xyz.feasible, ...
    '%s: final trajectory is marked dynamically infeasible.', name);
if ~cfg.speed.enable_global_time_scaling
    assert(abs(motion.constraint_scale - 1) <= tol, ...
        '%s: global time scaling was applied while disabled.', name);
end

dt = diff(motion.time);
if numel(dt) > 1
    nonfinal_deviation = abs(dt(1:end-1) - cfg.interpolation.Ts);
    [maximum_deviation, deviation_id] = max(nonfinal_deviation);
    time_step_tolerance = max([10 * eps(max(abs(motion.time))), ...
        cfg.interpolation.Ts * 1e-10, eps]);
    assert(maximum_deviation <= time_step_tolerance, ...
        ['%s: non-final time steps do not equal Ts; maximum deviation ' ...
        'is %.9g at time index %d (dt %.17g, Ts %.17g, tolerance %.9g).'], ...
        name, maximum_deviation, deviation_id, dt(deviation_id), ...
        cfg.interpolation.Ts, time_step_tolerance);
end
end

function item = make_report(name, motion, xyz, iterations)
item.name = string(name);
item.passed = true;
item.total_time = motion.time(end);
item.lmsc_count = numel(motion.lmsc.indices);
item.spu_count = numel(motion.spus);
item.constraint_iterations = iterations;
item.global_time_scale = motion.constraint_scale;
item.max_path_ratio = max([motion.validation.max_velocity_ratio, ...
    motion.validation.max_acceleration_ratio, motion.validation.max_jerk_ratio]);
item.max_xyz_ratio = max([xyz.max_velocity_ratio, xyz.max_acceleration_ratio, ...
    xyz.max_jerk_ratio, xyz.max_snap_ratio]);
end

function item = test_temporary_pareto_export(cfg)
assert(isfile(cfg.files.chromosome_final), ...
    'Pareto export test requires chromosome_final.txt.');
chromosome = load(cfg.files.chromosome_final);
expected_columns = cfg.nsga.num_variables + 3 + 2;
assert(size(chromosome, 2) == expected_columns, ...
    ['chromosome_final.txt has an incompatible column count. Rerun ' ...
    'main_function after changing the chromosome dimensions.']);
% Export mechanics do not require re-evaluating the entire production
% population. A small deterministic subset keeps the regression fast.
chromosome = chromosome(1:min(5, size(chromosome, 1)), :);

temporary_output = tempname;
mkdir(temporary_output);
cleanup = onCleanup(@() remove_temporary_output(temporary_output));
cfg.output_dir = temporary_output;
candidates = list_pareto_candidates(chromosome, cfg);
assert(~isempty(candidates), 'No Pareto candidate is available for export.');
[cached_candidates, cache_used] = list_pareto_candidates(chromosome, cfg);
assert(cache_used && isequaln(cached_candidates, candidates), ...
    'Pareto raw-objective cache was not reused.');
assert(isfile(fullfile(temporary_output, 'pareto_candidates_cache.mat')), ...
    'Pareto raw-objective cache file was not created.');
selected_id = candidates(1, 1);
chromosome_row = candidates(1, 5);
x = chromosome(chromosome_row, 1:cfg.nsga.num_variables);
result = evaluate_trajectory(x, cfg, true);
if cfg.lmsc_jerk_boundary.enabled && ...
        cfg.lmsc_jerk_boundary.evaluate_during_objective
    assert(isfield(result, 'lmsc_jerk_boundary_search') && ...
            result.lmsc_jerk_boundary_search.evaluated_during_objective, ...
        'Pareto re-evaluation skipped the shared endpoint-jerk decision.');
    selected_utilization = ...
        result.lmsc_jerk_boundary_search.selected_utilization;
else
    selected_utilization = x(end);
end
assert(abs(candidates(1, end) - selected_utilization) <= eps, ...
    'Pareto candidate did not record its endpoint-jerk decision variable.');
expected_raw_objectives = [result.raw_objectives.time, ...
    result.raw_objectives.error, result.raw_objectives.vibration];
objective_tolerance = 1e-9 * max(1, abs(expected_raw_objectives));
assert(all(abs(candidates(1, 2:4) - expected_raw_objectives) <= ...
    objective_tolerance), ...
    'Pareto candidate table contains penalized instead of raw objectives.');
verify_motion('pareto_candidate_export', result.motion, result.xyz, ...
    result.constraints, result.arc.S(end), cfg);
export_results(result, chromosome, candidates, selected_id, cfg);
objective_table = readtable(fullfile(temporary_output, ...
    sprintf('solution_%03d', selected_id), ...
    'exported_solution_objectives.csv'));
reevaluated = [objective_table.reevaluated_time, ...
    objective_table.reevaluated_error, ...
    objective_table.reevaluated_vibration];
assert(all(abs(reevaluated - candidates(1, 2:4)) <= ...
        objective_tolerance), ...
    'Exported objectives differ from the optimized Pareto candidate.');
front_table = readtable(fullfile(temporary_output, 'pareto_front.csv'));
front_values = [front_table.Time, front_table.Error, front_table.Vibration];
assert(size(front_values, 1) == size(candidates, 1) && ...
        all(abs(front_values - candidates(:, 2:4)) <= ...
        1e-9 * max(1, abs(candidates(:, 2:4))), 'all'), ...
    'pareto_front.csv contains penalized instead of raw objectives.');

solution_dir = fullfile(temporary_output, sprintf('solution_%03d', selected_id));
required = {'smooth_path.csv','position.csv','velocity.csv','acceleration.csv','jerk.csv', ...
    'curvature.csv','path_motion.csv','jerk_components.csv','snap.csv', ...
    'crackle.csv', ...
    'resonance_spectrum.csv','selected_solution.csv', ...
    'exported_solution_objectives.csv', ...
    'constraint_status.csv','vibration_metrics.csv','speed_constraints.csv', ...
    'lmsc_points.csv','spu_info.csv','lmsc_jerk_boundary_search.csv', ...
    'lmsc_jerk_boundary_candidates.csv','lmsc_jerk_boundary_values.csv', ...
    'spu_peak_jerk_boundary_values.csv'};
for i = 1:numel(required)
    assert(isfile(fullfile(solution_dir, required{i})), ...
        'Missing exported file: %s', required{i});
end
item = make_report('pareto_candidate_export', result.motion, result.xyz, ...
    result.constraint.iterations);
end

function test_shared_lmsc_jerk_transition(cfg)
assert(cfg.lmsc_jerk_boundary.numerical_peak_plateau_time_tolerance > 0 && ...
        cfg.lmsc_jerk_boundary.numerical_peak_plateau_time_tolerance < ...
        cfg.interpolation.Ts, ...
    'The numerical peak-plateau tolerance must remain below one Ts sample.');
time = linspace(0, 0.2, 101)';
[S_legacy, V_legacy, A_legacy, J_legacy] = ...
    evaluate_septic_transition(time, 0, 20, 80, 0.2);
[S_zero, V_zero, A_zero, J_zero] = ...
    evaluate_septic_transition(time, 0, 20, 80, 0.2, 0, 0);
zero_tolerance = 100 * eps(max([1; abs(S_legacy); abs(V_legacy); ...
    abs(A_legacy); abs(J_legacy)]));
assert(max(abs([S_zero-S_legacy; V_zero-V_legacy; ...
        A_zero-A_legacy; J_zero-J_legacy])) <= zero_tolerance, ...
    'Explicit zero endpoint jerk changed the legacy seventh-order law.');

shared_jerk = 0.6 * cfg.limits.Jmax;
left_duration = 0.18;
right_duration = 0.16;
[~, left_velocity, left_acceleration, left_jerk, left_snap] = ...
    evaluate_septic_transition([0; left_duration], 0, 90, 30, ...
    left_duration, 0, shared_jerk);
[~, right_velocity, right_acceleration, right_jerk, right_snap] = ...
    evaluate_septic_transition([0; right_duration], 0, 30, 85, ...
    right_duration, shared_jerk, 0);
boundary_tolerance = max(cfg.limits.Jmax * 1e-9, 1e-6);
assert(abs(left_velocity(end) - right_velocity(1)) <= ...
        cfg.speed.velocity_tolerance && ...
        abs(left_acceleration(end) - right_acceleration(1)) <= ...
        boundary_tolerance && ...
        abs(left_jerk(end) - shared_jerk) <= boundary_tolerance && ...
        abs(right_jerk(1) - shared_jerk) <= boundary_tolerance && ...
        abs(left_jerk(end) - right_jerk(1)) <= boundary_tolerance && ...
        abs(left_snap(end)) <= boundary_tolerance && ...
        abs(right_snap(1)) <= boundary_tolerance, ...
    'The two adjacent transitions do not share a continuous LMSC jerk.');

peak_jerk = -0.5 * cfg.limits.Jmax;
left_duration = 0.17;
right_duration = 0.19;
[~, left_velocity, left_acceleration, left_jerk, left_snap] = ...
    evaluate_septic_transition([0; left_duration], 0, 25, 95, ...
    left_duration, 0, peak_jerk);
[~, right_velocity, right_acceleration, right_jerk, right_snap] = ...
    evaluate_septic_transition([0; right_duration], 0, 95, 35, ...
    right_duration, peak_jerk, 0);
assert(abs(left_velocity(end) - right_velocity(1)) <= ...
        cfg.speed.velocity_tolerance && ...
        abs(left_acceleration(end) - right_acceleration(1)) <= ...
        boundary_tolerance && ...
        abs(left_jerk(end) - peak_jerk) <= boundary_tolerance && ...
        abs(right_jerk(1) - peak_jerk) <= boundary_tolerance && ...
        abs(left_jerk(end) - right_jerk(1)) <= boundary_tolerance && ...
        abs(left_snap(end)) <= boundary_tolerance && ...
        abs(right_snap(1)) <= boundary_tolerance, ...
    'The two transitions do not share a continuous negative peak jerk.');
end

function remove_temporary_output(folder)
if isfolder(folder)
    rmdir(folder, 's');
end
end

function test_unique_chromosome_floor(cfg)
M = 3;
V = cfg.nsga.num_variables;
pop = max(40, cfg.nsga.min_unique_chromosomes + 1);
columns = V + M + 2;
intermediate = zeros(pop + cfg.nsga.min_unique_chromosomes, columns);
base = [cfg.bounds.weights_lb cfg.bounds.time_lb ...
    cfg.bounds.jerk_utilization_lb];
intermediate(:, 1:V) = repmat(base, size(intermediate, 1), 1);
intermediate(1:pop, V + M + 1) = 1;
intermediate(1:pop, V + M + 2) = Inf;
for i = 1:cfg.nsga.min_unique_chromosomes
    row = pop + i;
    variable_id = cfg.nsga.num_weights + 1;
    intermediate(row, variable_id) = min( ...
        base(variable_id) + 0.01 * i, cfg.bounds.time_ub(1));
    intermediate(row, V + M + 1) = 2;
    intermediate(row, V + M + 2) = 1;
end

selected = replace_chromosome(intermediate, M, V, pop, ...
    cfg.nsga.min_unique_chromosomes);
assert(size(unique(selected(:, 1:V), 'rows'), 1) >= ...
    cfg.nsga.min_unique_chromosomes, ...
    'Environmental selection did not preserve the minimum unique chromosomes.');
assert(abs(cfg.nsga.mutation_probability - 0.20) <= eps, ...
    'The configured mutation probability is not 20 percent.');
end

function test_dynamic_dimensions(cfg)
assert(cfg.dynamic_dimensions.enabled, ...
    'Dynamic path dimensions are not enabled.');
assert(cfg.nurbs.num_control_points >= ...
        cfg.dynamic_dimensions.min_control_points && ...
        cfg.nurbs.num_control_points <= ...
        cfg.dynamic_dimensions.max_control_points, ...
    'Dynamic NURBS control-point count is outside its configured bounds.');
assert(cfg.nsga.num_time_nodes >= ...
        cfg.dynamic_dimensions.min_speed_nodes && ...
        cfg.nsga.num_time_nodes <= ...
        cfg.dynamic_dimensions.max_speed_nodes, ...
    'Dynamic speed-node count is outside its configured bounds.');
assert(cfg.nsga.num_variables == cfg.nurbs.num_control_points + ...
        cfg.nsga.num_time_nodes + 1 && ...
        cfg.nsga.num_jerk_utilization_variables == 1, ...
    'Dynamic chromosome dimension is inconsistent.');
assert(numel(cfg.bounds.weights_lb) == cfg.nurbs.num_control_points && ...
        numel(cfg.bounds.time_lb) == cfg.nsga.num_time_nodes && ...
        cfg.bounds.jerk_utilization_lb == 0 && ...
        cfg.bounds.jerk_utilization_ub == double( ...
            cfg.lmsc_jerk_boundary.enabled && ...
            cfg.lmsc_jerk_boundary.evaluate_during_objective) && ...
        numel(cfg.nsga.reference_decision) == cfg.nsga.num_variables && ...
        cfg.nsga.reference_decision(end) == 0, ...
    'Dynamic variable bounds have inconsistent lengths.');
if cfg.nurbs.force_unit_weights
    assert(all(cfg.bounds.weights_lb == 1) && ...
            all(cfg.bounds.weights_ub == 1), ...
        'Unit-weight B-spline bounds are not fixed at one.');
else
    assert(all(cfg.bounds.weights_lb == 0.1) && ...
            all(cfg.bounds.weights_ub == 1.0), ...
        'NURBS weight bounds are not [0.1, 1.0].');
end
assert(isfield(cfg.nurbs, 'base_control_points') && ...
        size(cfg.nurbs.base_control_points, 1) == ...
        cfg.nurbs.num_control_points, ...
    'The dynamically fitted NURBS control points are missing.');
assert(numel(cfg.nurbs.base_knots) == cfg.nurbs.num_control_points + ...
        cfg.nurbs.degree + 1 && all(diff(cfg.nurbs.base_knots) >= 0), ...
    'The dynamically fitted NURBS knot vector is invalid.');
internal_knots = cfg.nurbs.base_knots(cfg.nurbs.degree + 2: ...
    end - cfg.nurbs.degree - 1);
[~, ~, knot_group] = unique(internal_knots);
assert(isempty(knot_group) || max(accumarray(knot_group(:), 1)) <= ...
        cfg.nurbs.corner_knot_multiplicity, ...
    'An internal knot has greater multiplicity than configured.');
probe_u = linspace(0, 1, 101)';
basis = bspline_basis_matrix(probe_u, cfg.nurbs.num_control_points, ...
    cfg.nurbs.degree, cfg.nurbs.base_knots);
assert(max(abs(sum(basis, 2) - 1)) <= 1e-10, ...
    'The B-spline basis does not form a partition of unity.');
assert(isfinite(cfg.dynamic_dimensions.baseline_error) && ...
        (~cfg.dynamic_dimensions.baseline_target_met || ...
        cfg.dynamic_dimensions.baseline_error <= ...
        cfg.constraints.max_contour_error), ...
    'The dynamic baseline-error diagnostic is inconsistent.');
end

function test_dynamic_lmsc_clustering(cfg)
S = (0:20)';
v_limit = 500 * ones(size(S));
kappa = zeros(size(S));
dynamic_indices = [10; 11; 12];
v_limit(dynamic_indices) = [120; 100; 80];
kappa(dynamic_indices) = [0.1; 0.2; 0.3];
lmsc = detect_lmsc_points(S, v_limit, kappa, cfg, dynamic_indices);
kept_dynamic = lmsc.indices(lmsc.is_dynamic);
assert(isequal(kept_dynamic, 12), ...
    'Adjacent dynamically forced LMSC points were not clustered.');
assert(isequal(lmsc.indices([1 end]), [1; numel(S)]), ...
    'Endpoint preservation removed an interior dynamic LMSC.');

[small_spacing, ~, small_floor] = dynamic_lmsc_spacing(100, 99, S, cfg);
[large_spacing, transition_distance, large_floor] = ...
    dynamic_lmsc_spacing(100, 50, S, cfg);
assert(large_spacing > small_spacing && transition_distance > 0, ...
    'Dynamic LMSC spacing does not increase with transition demand.');
expected_large_spacing = cfg.speed.lmsc_merge_distance_factor * max( ...
    cfg.speed.lmsc_transition_distance_factor * transition_distance, ...
    large_floor);
assert(abs(large_spacing - expected_large_spacing) <= ...
        1e-12 * max(1, expected_large_spacing) && ...
        cfg.speed.lmsc_merge_distance_factor > 1, ...
    'The wider dynamic LMSC merge threshold was not applied.');
assert(abs(small_floor - cfg.speed.lmsc_min_sample_intervals) <= eps && ...
        abs(large_floor - small_floor) <= eps, ...
    'Dynamic LMSC sampling floor is inconsistent with the path resolution.');

fine_S = (0:0.1:2)';
[~, ~, fine_floor] = dynamic_lmsc_spacing(100, 100, fine_S, cfg);
assert(fine_floor < small_floor, ...
    'Dynamic LMSC sampling floor does not adapt to path resolution.');
end

function test_xyz_vibration_metric(cfg)
jerk = [3 0 4; -3 4 -4];
metrics = xyz_vibration_metric(jerk, cfg);
expected_axis_rms = sqrt(mean(jerk.^2, 1));
legacy_combined_rms = sqrt(mean(sum(jerk.^2, 2)));
assert(max(abs(metrics.axis_rms - expected_axis_rms)) <= 1e-12, ...
    'The decomposed X/Y/Z vibration RMS values are incorrect.');
assert(abs(metrics.combined_rms - legacy_combined_rms) <= 1e-12, ...
    'Equal XYZ weights no longer reproduce the original vector jerk RMS.');
expected_peak = max(vecnorm(jerk, 2, 2));
expected_objective = legacy_combined_rms + ...
    cfg.objectives.vibration_peak_weight * expected_peak;
assert(abs(metrics.combined_peak - expected_peak) <= 1e-12 && ...
        abs(metrics.objective_value - expected_objective) <= 1e-12, ...
    'The vibration peak term was not included in the objective.');
assert(abs(sum(metrics.contribution_ratio) - 1) <= 1e-12, ...
    'The XYZ vibration contribution ratios do not sum to one.');

weighted_cfg = cfg;
weighted_cfg.objectives.vibration_axis_weights = [1 2 0.5];
weighted = xyz_vibration_metric(jerk, weighted_cfg);
expected_weighted = norm(expected_axis_rms .* [1 2 0.5], 2);
assert(abs(weighted.combined_rms - expected_weighted) <= 1e-12, ...
    'The configured XYZ vibration weights were not applied.');

snap_cfg = cfg;
snap_cfg.resonance.enabled = false;
snap_time = [0; 0.002; 0.004];
snap_jerk = [0 0 0; 700 0 0; 1400 0 0];
snap_metrics = xyz_vibration_metric(snap_jerk, snap_cfg, snap_time);
expected_snap_ratio = 350000 / snap_cfg.limits.xyz_smax(1);
assert(abs(snap_metrics.axis_snap_peak(1) - 350000) <= 1e-9 && ...
        abs(snap_metrics.axis_snap_ratio(1) - expected_snap_ratio) <= 1e-12 && ...
        snap_metrics.snap_feasible, ...
    'The XYZ snap hard-limit ratio is incorrect.');

crackle_time = (0:4)' * 0.002;
crackle_jerk = [(0:4)'.^3, zeros(5, 2)];
crackle_metrics = xyz_vibration_metric( ...
    crackle_jerk, snap_cfg, crackle_time, [], true);
assert(crackle_metrics.axis_crackle_rms(1) > 0 && ...
        crackle_metrics.combined_equivalent_crackle > 0 && ...
        any(abs(crackle_metrics.crackle(:, 1)) > 0), ...
    'The XYZ Crackle smoothness metric was not evaluated.');
end

function test_xyz_snap_limit_switch(cfg)
switch_cfg = cfg;
switch_cfg.limits.xyz_vmax = [Inf Inf Inf];
switch_cfg.limits.xyz_amax = [Inf Inf Inf];
switch_cfg.limits.xyz_jmax = [Inf Inf Inf];
switch_cfg.limits.xyz_smax = [1 1 1];

S = (0:4)';
points = [S, zeros(size(S)), zeros(size(S))];
motion.time = (0:4)' * cfg.interpolation.Ts;
motion.S = S;
motion.path_velocity = zeros(size(S));
motion.path_acceleration = zeros(size(S));
motion.path_jerk = [0; 0; 1; 0; 0];

switch_cfg.constraints.enable_xyz_snap_limit = true;
enforced = xyz_motion(points, S, motion, switch_cfg);
assert(enforced.max_snap_ratio > 1 && ~enforced.feasible && ...
        enforced.max_enforced_snap_ratio == enforced.max_snap_ratio, ...
    'Enabled XYZ snap hard limit did not reject an over-limit trajectory.');

switch_cfg.constraints.enable_xyz_snap_limit = false;
diagnostic_only = xyz_motion(points, S, motion, switch_cfg);
assert(diagnostic_only.max_snap_ratio == enforced.max_snap_ratio && ...
        diagnostic_only.max_enforced_snap_ratio == 0 && ...
        diagnostic_only.feasible, ...
    ['Disabled XYZ snap hard limit did not preserve diagnostics while ' ...
    'removing snap from feasibility.']);
end

function test_analytic_nurbs_derivatives()
control_points = [0 0 0; 1/3 0 0; 2/3 1/3 0; 1 1 1];
weights = ones(1, 4);
degree = 3;
knots = [0 0 0 0 1 1 1 1];
u = [0.2; 0.5; 0.8];
derivatives = evaluate_nurbs_derivatives( ...
    control_points, weights, degree, knots, u, 3);
expected_0 = [u, u.^2, u.^3];
expected_1 = [ones(size(u)), 2*u, 3*u.^2];
expected_2 = [zeros(size(u)), 2*ones(size(u)), 6*u];
expected_3 = [zeros(size(u)), zeros(size(u)), 6*ones(size(u))];
expected = cat(3, expected_0, expected_1, expected_2, expected_3);
assert(max(abs(derivatives - expected), [], 'all') <= 1e-11, ...
    'Analytic NURBS parameter derivatives are incorrect.');

line_curve.control_points = [0 0 0; 1 2 0; 2 4 0; 3 6 0];
line_curve.weights = [1 2 0.8 1.5];
line_curve.degree = degree;
line_curve.knots = knots;
line_derivatives = nurbs_arc_derivatives(line_curve, u);
expected_tangent = repmat([1 2 0] / sqrt(5), numel(u), 1);
assert(max(abs(line_derivatives.q_s - expected_tangent), [], 'all') <= 1e-10 && ...
        max(abs(line_derivatives.q_ss), [], 'all') <= 1e-9 && ...
        max(abs(line_derivatives.q_sss), [], 'all') <= 1e-8, ...
    'Analytic NURBS arc-length derivatives are incorrect on a straight line.');
end

function test_geometric_jerk_speed_limit(cfg)
S = linspace(0, 1, 5)';
kappa = zeros(size(S));
tangent = repmat([1 0 0], numel(S), 1);
derivatives.q_sss = zeros(numel(S), 3);
derivatives.q_sss(:, 2) = 8;
constraints = generate_velocity_constraints(kappa, tangent, cfg, S, ...
    ones(1, cfg.nsga.num_time_nodes), derivatives);
expected = nthroot(cfg.limits.xyz_jmax(2) / 8, 3);
assert(max(abs(constraints.v_geometric_jerk - expected)) <= 1e-12, ...
    'The geometric XYZ jerk speed limit is incorrect.');
assert(all(constraints.base_active_constraint == "geometric_jerk"), ...
    'The geometric jerk speed limit was not marked as active.');
end

function test_pareto_time_filter(cfg)
raw_objectives = [1 3 4; 9.999 2 3; 10 1 2; 10.001 0 1; 5 4 5];
[keep, minimum_time, maximum_time] = filter_pareto_by_time( ...
    raw_objectives, cfg.pareto.max_time_ratio);
assert(isequal(keep, [true; true; true; false; true]), ...
    'The Pareto time-ratio filter retained an invalid candidate.');
assert(minimum_time == 1 && maximum_time == 10, ...
    'The Pareto time-ratio threshold is incorrect.');
end

function remove_legacy_vecnorm_shadow(project_root)
legacy_folder = fullfile(project_root, 'NURBS', 'nurbs', 'inst');
path_entries = strsplit(path, pathsep);
if any(strcmpi(path_entries, legacy_folder))
    rmpath(legacy_folder);
end
end
